name: Check and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # Remove npm cache configuration
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Build sdk-core
      run: pnpm run build
      working-directory: ./packages/sdk-core

    - name: Build sdk-react-hooks
      run: pnpm run build
      working-directory: ./packages/sdk-react-hooks

    - name: Build sdk-react-ui
      run: pnpm run build
      working-directory: ./packages/sdk-react-ui
